# Generated by Django 3.2 on 2022-10-25 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_catalogimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='inactive_image',
            field=models.ImageField(default=0, upload_to='manufacturers/inactive/'),
            preserve_default=False,
        ),
    ]
