# Generated by Django 3.2 on 2022-10-26 10:10

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_characteristicvar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteristicvar',
            name='title',
            field=tinymce.models.HTMLField(),
        ),
    ]
