# Generated by Django 3.2 on 2022-10-26 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('products', '0005_alter_characteristicvar_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CharacteristicVar',
        ),
    ]
