# Generated by Django 3.2 on 2022-10-26 10:14

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_delete_characteristicvar'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacteristicVar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', tinymce.models.HTMLField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristic_vars', to='products.product')),
            ],
        ),
    ]
