# Generated by Django 3.2 on 2022-10-26 10:28

import cms.models.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('products', '0007_characteristicvar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteristicvar',
            name='title',
            field=cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, slotname='characteristic_var', to='cms.placeholder'),
        ),
    ]
