# Generated by Django 3.2 on 2022-10-26 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_characteristicvar_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteristicvar',
            name='title',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
