# Generated by Django 3.2 on 2022-10-26 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_characteristicvar_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='marks',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
