# Generated by Django 3.2 on 2022-10-26 15:02

import cms.models.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('products', '0013_auto_20221026_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='my_placeholder',
        ),
        migrations.AddField(
            model_name='product',
            name='characteristic',
            field=cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, slotname='product_characteristic', to='cms.placeholder'),
        ),
    ]
