# Generated by Django 3.2 on 2022-10-26 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20221026_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='characteristic',
        ),
        migrations.CreateModel(
            name='ProductCharacteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('var1', models.CharField(blank=True, max_length=100, null=True)),
                ('var2', models.CharField(blank=True, max_length=100, null=True)),
                ('var3', models.CharField(blank=True, max_length=100, null=True)),
                ('var4', models.CharField(blank=True, max_length=100, null=True)),
                ('var5', models.CharField(blank=True, max_length=100, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristic', to='products.product')),
            ],
        ),
    ]
