# Generated by Django 3.2 on 2022-10-27 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('products', '0016_productorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinate',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='products_coordinate', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(max_length=100)),
                ('coord_long', models.DecimalField(decimal_places=20, max_digits=25)),
                ('coord_lat', models.DecimalField(decimal_places=20, max_digits=25)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
