# Generated by Django 3.2 on 2022-10-27 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_delete_coordinate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('coord_long', models.DecimalField(decimal_places=20, max_digits=25)),
                ('coord_lat', models.DecimalField(decimal_places=20, max_digits=25)),
            ],
        ),
    ]
