# Generated by Django 3.2 on 2022-11-04 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_coordinate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCsv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.FileField(upload_to='csv/')),
            ],
        ),
    ]
