# Generated by Django 3.2 on 2022-11-04 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_rename_short_descrition_product_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.FilePathField(default='catalog_product.jpg', path='/media/products/'),
            preserve_default=False,
        ),
    ]
