# Generated by Django 3.2 on 2022-11-04 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_auto_20221104_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.FilePathField(default='catalog_product.jpg', path='media/products/'),
            preserve_default=False,
        ),
    ]
