# Generated by Django 3.2 on 2022-11-04 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_product_image2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image2',
            field=models.FilePathField(blank=True, null=True, path='media/products/'),
        ),
    ]
