# Generated by Django 3.2 on 2022-11-04 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_rename_image2_product_image_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='marks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
