# Generated by Django 3.2 on 2022-11-04 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_alter_product_image_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_choice',
            field=models.FilePathField(blank=True, null=True, path='media/products/'),
        ),
    ]
