# Generated by Django 3.2 on 2022-11-04 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_alter_product_image_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AlterField(
            model_name='product',
            name='image_choice',
            field=models.FilePathField(blank=True, null=True, path='/Users/alexandrzhyliuk/Documents/cases/sodox/cms/sodox/media/products/'),
        ),
    ]
