# Generated by Django 3.2 on 2022-11-06 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_auto_20221104_1858'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductCsv',
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.FilePathField(path='/Users/alexandrzhyliuk/Documents/cases/sodox/cms/sodox/media/products/images/'),
        ),
    ]
