# Generated by Django 3.2 on 2022-11-28 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_auto_20221128_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='image',
            field=models.FilePathField(blank=True, null=True, path='/Users/alexandrzhyliuk/Documents/cases/sodox/cms/sodox/media/products/', verbose_name='Изображение'),
        ),
    ]
