# Generated by Django 3.2 on 2022-11-28 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_subcategory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='advantages',
            field=models.TextField(default=1, verbose_name='Преимущества'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='recommendation',
            field=models.TextField(default=1, verbose_name='Рекомендация'),
            preserve_default=False,
        ),
    ]
