# Generated by Django 3.2 on 2022-11-28 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_auto_20221128_1039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nomenclature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Название')),
                ('var1', models.CharField(blank=True, max_length=128, null=True)),
                ('var2', models.CharField(blank=True, max_length=128, null=True)),
                ('var3', models.CharField(blank=True, max_length=128, null=True)),
                ('var4', models.CharField(blank=True, max_length=128, null=True)),
                ('var5', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'verbose_name_plural': 'Номенклатура',
            },
        ),
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='coordinate',
            options={'verbose_name_plural': 'Координаты'},
        ),
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'verbose_name_plural': 'Производители'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name_plural': 'Подкатегории'},
        ),
        migrations.AddField(
            model_name='subcategory',
            name='description',
            field=models.TextField(default=1, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategory',
            name='review',
            field=models.TextField(default=1, verbose_name='Обзор'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Название'),
        ),
        migrations.CreateModel(
            name='NomenclatureRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=128, verbose_name='Название')),
                ('code', models.CharField(max_length=64, verbose_name='Код заказа')),
                ('var1', models.CharField(blank=True, max_length=128, null=True)),
                ('var2', models.CharField(blank=True, max_length=128, null=True)),
                ('var3', models.CharField(blank=True, max_length=128, null=True)),
                ('var4', models.CharField(blank=True, max_length=128, null=True)),
                ('var5', models.CharField(blank=True, max_length=128, null=True)),
                ('nomenclature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='products.nomenclature')),
            ],
            options={
                'verbose_name_plural': 'Строки номенклатуры',
            },
        ),
        migrations.AddField(
            model_name='nomenclature',
            name='subcategory',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.subcategory'),
        ),
    ]
