# Generated by Django 3.2 on 2022-11-28 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0035_auto_20221128_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomenclaturerow',
            name='model',
            field=models.CharField(max_length=256, verbose_name='Название'),
        ),
        migrations.CreateModel(
            name='Downloads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(max_length=256, verbose_name='Серии')),
                ('model', models.CharField(max_length=256, verbose_name='Модель')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='products.subcategory')),
            ],
            options={
                'verbose_name_plural': 'Загрузки',
            },
        ),
    ]
