# Generated by Django 3.2 on 2022-11-28 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0036_auto_20221128_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloads',
            name='file',
            field=models.FilePathField(blank=True, null=True, path='/Users/alexandrzhyliuk/Documents/cases/sodox/cms/sodox/media/products/', verbose_name='Файл'),
        ),
    ]
